### PR TITLE
Fix compilation warnings

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by cpinter** [comment]
Great, thank you!

**Comment by jcfr** [comment]
As a side note, these vtkMRMLRoomsEyeViewNode attributes are not used:

```
  int ApplicatorHolderVisibility;
  int ElectronApplicatorVisibility;
```

**Comment by cpinter** [comment]
That module has bene in progress for a while, so I'm not surprised. I took it out from the experimental modules so that the factory runs its tests - one was failing for a while - and because it's a neat module nevertheless.
Maybe I'll just comment out those variables.

**Comment by cpinter** [comment]
@jcfr FYI I just added the initialization, XML, Copy etc for these variables
https://github.com/SlicerRt/SlicerRT/commit/e14c55ed03ef57183689199686d3f7c7d5dda4a1

**Pull request merged**
