### PR TITLE
ENH: Update DRR RT Beam parameters from 3D camera node

### PR DESCRIPTION
**Pull request by MichaelColonel**
Direction cosines of vtkCamera are used to calculate a new beam transform. 

Updated beam parameters from 3D camera are: 

- Gantry Angle;
- Patient Support Rotation (Couch) Angle;
-  Source-Axis Distance.

Minor change in onBeamsEyeViewButtonClicked method of RoomsEyeView module GUI.

### CODE REVIEW

**Comment by cpinter** [comment]
Thanks for the new contribution! This week I won't have time to review the code, so it would help a lot if you added a detailed description in the commit message. Or if someone can find the time to review this it would be welcome @Sunderlandkyl @gregsharp @lassoan . Thanks!

**Comment by MichaelColonel** [comment]
I've added a more detailed description into commit message.

**Comment by cpinter** [comment]
Thanks, I'm OK with merging this. It seems to be low-risk because it is an additional feature, and quite a nice one too.

Please make sure no new tests fail and confirm.

I'll give a little time for the others mentioned above to take a look if they want.

**Comment by MichaelColonel** [comment]
Failed tests under linux:
1:qSlicerBeamsModuleGenericTest
2:qSlicerBeamsModuleWidgetGenericTest
6:vtkSlicerIsodoseModuleLogicTest_EclipseProstate
39:vtkSlicerSegmentComparisonModuleLogicTest_EclipseProstate_Transformed
47:py_nomainwindow_PlmProtonDoseEngineTest

**Comment by Sunderlandkyl** [comment]
The changes look good to me.

**Pull request merged**
