### PR TITLE
Fix implicit instantiation of std::array for Windows and MacOS build

### PR DESCRIPTION
**Pull request by MichaelColonel**

### CODE REVIEW

**Comment by cpinter** [comment]
Could you please explain in the commit message the reason and purpose of this change?

**Comment by MichaelColonel** [comment]
There are several errors for [Windows](http://slicer.cdash.org/viewBuildError.php?buildid=1857171) and [MacOS](http://slicer.cdash.org/viewBuildError.php?buildid=1857245) builds. [Linux](http://slicer.cdash.org/viewBuildError.php?buildid=1856968) build doesn't have such problem, since some c++11 headers are included implicitly. I can only test linux distribution at home.

**Comment by cpinter** [comment]
Then please add this into the commit message, and change the prefix to "COMP:"

**Comment by MichaelColonel** [comment]
Could you check that commit name is correct now?

**Comment by cpinter** [comment]
I don't mean to be nitpicking here, but the commit message is very generic. You already described it in greater detail in the previous commit message and then here in a comment. Could you just copy-paste it there? It is not advantageous trying to be as concise as possible in the commit messages, but the opposite! Thank you!

**Comment by MichaelColonel** [comment]
I have added a more detailed commit message.

**Comment by cpinter** [comment]
Excellent, thank you very much!

**Pull request merged**
