### PR TITLE
ENH: GUI upgrade of perspective projection calculation:

### PR DESCRIPTION
**Pull request by MichaelColonel**
* QTableWidget to represent projected control points;
* Project only selected or all control points;
* Flag to created a new markups fiducial node for projected points.

### CODE REVIEW

**Comment by MichaelColonel** [comment]
New interface

image

**Comment by cpinter** [comment]
After a very quick glance it looks OK to me. One question so far: was there a specific reason for removing `ModuleWindowInitialized`? Thanks!

**Comment by MichaelColonel** [comment]
Module is quite simple and it doesn't require any specific GUI initiation. The GUI doesn't show beam node correctly if parameterNode was created in python console if you switch into module GUI for the first time with `ModuleWindowInitialized`.

**Comment by cpinter** [comment]
Makes sense, thanks! I won't be able to do a thorough review, but since you are the main user/developer of the DRR module I'd simply accept this change. @Sunderlandkyl @lassoan please review if interested. I'll merge it in a day or two (unless you need it merged asap @MichaelColonel in which case I can do it now). Thanks again!

**Comment by MichaelColonel** [comment]
I thick it could be merged, so it could be tested by the user.

**Comment by lassoan** [comment]
Thank you for all your hard work.

**Pull request merged**
