### PR TITLE
ENH: Temporary fix of compilation error after ITK-5.3 update

### PR DESCRIPTION
**Pull request by MichaelColonel**
Plastimatch [PR](https://gitlab.com/plastimatch/plastimatch/-/merge_requests/29) must be merged before this PR.

### CODE REVIEW

**Comment by cpinter** [comment]
Thanks for working on this @MichaelColonel ! It will also be necessary to update the Plastimatch hash I guess.

**Comment by MichaelColonel** [comment]
Even if the Plastimatch fix is acceptable and correct, it's not only issue. When i tried to load CT data with RT-STRUCT the program crashed, and i don't think that it was the Plastimatch problem. I will try to check what went wrong.

**Comment by gregsharp** [comment]
Thanks @MichaelColonel !  Do you know which file is redefining POSIX?  itkImageFileReader is included in a lot of files which you did not patch.

**Comment by MichaelColonel** [comment]
> Thanks @MichaelColonel ! Do you know which file is redefining POSIX? itkImageFileReader is included in a lot of files which you did not patch.

No, not yet.

**Comment by MichaelColonel** [comment]
@gregsharp

For the [itk_tps](https://gitlab.com/plastimatch/plastimatch/-/blob/master/src/plastimatch/register/itk_tps.h) file the cmake preprocessor output shows that there is a[ header from dlib library](https://gitlab.com/plastimatch/plastimatch/-/blob/master/libs/dlib-19.1/dlib/platform.h#L37-L43) that contains 
```
#define POSIX
```

**Comment by lassoan** [comment]
Users keep complaining - see https://discourse.slicer.org/t/slicerrt-extension-installation/22497/2

If this temporary solution works then please merge it.

SlicerRT has about 9 downloads every day for each preview release, so even with a few-day outage we turn away dozens of potential users, but it has been around for more than two weeks now. Once the new stable release is out, users can use the latest stable release, but right now that is so old that we cannot really recommend it to users.

**Comment by MichaelColonel** [comment]
I've tested with patched Plastimatch and this PR. Slicer 4.13.0-2022-03-07 r30665 / 99bba70, GCC-11.2.

If the fix is needed ASAP, then i can temporary modify [External_Plastimatch.cmake](https://github.com/SlicerRt/SlicerRT/blob/master/SuperBuild/External_Plastimatch.cmake#L28-L38) to use [my Plastimatch branch](https://gitlab.com/MichaelColonel/plastimatch/-/tree/tmp-itk5.3-fix). 


Failed tests:
```
74% tests passed, 18 tests failed out of 68

Label Time Summary:
plastimatch_slicer_drr                    =   0.26 sec*proc (1 test)
qSlicerBeamsModule                        =  26.05 sec*proc (3 tests)
qSlicerDicomRtImportExportModule          =  30.75 sec*proc (2 tests)
qSlicerDicomSroImportExportModule         =  14.78 sec*proc (2 tests)
qSlicerDoseAccumulationModule             =  14.55 sec*proc (2 tests)
qSlicerDoseComparisonModule               =  21.20 sec*proc (2 tests)
qSlicerDoseVolumeHistogramModule          =  14.26 sec*proc (2 tests)
qSlicerDosxyzNrc3dDoseFileReaderModule    =  12.17 sec*proc (2 tests)
qSlicerDrrImageComputationModule          =  21.41 sec*proc (3 tests)
qSlicerIsodoseModule                      =  15.73 sec*proc (2 tests)
qSlicerPlanarImageModule                  =  10.80 sec*proc (2 tests)
qSlicerPlastimatchPyModule                =  12.82 sec*proc (2 tests)
qSlicerPlmProtonDoseEngineModule          =  27.05 sec*proc (2 tests)
qSlicerRoomsEyeViewModule                 =  21.43 sec*proc (3 tests)
qSlicerSegmentComparisonModule            =  20.71 sec*proc (2 tests)
qSlicerVffFileReaderModule                =  13.13 sec*proc (2 tests)

Total Test time (real) = 383.51 sec

The following tests FAILED:
	  1 - qSlicerBeamsModuleGenericTest (Failed)
	  2 - qSlicerBeamsModuleWidgetGenericTest (Failed)
	  4 - qSlicerIsodoseModuleGenericTest (Failed)
	  5 - qSlicerIsodoseModuleWidgetGenericTest (Failed)
	  6 - vtkSlicerIsodoseModuleLogicTest_EclipseProstate (Failed)
	 12 - py_DicomRtImportTest (Failed)
	 18 - vtkSlicerDoseVolumeHistogramModuleLogicTest_EclipseProstate_Base (Failed)
	 19 - vtkSlicerDoseVolumeHistogramModuleLogicTest_EclipseProstate_CERR (Failed)
	 20 - vtkSlicerDoseVolumeHistogramModuleLogicTest_EclipseEnt_CERR (Failed)
	 22 - vtkSlicerDoseVolumeHistogramModuleLogicTest_EclipseEnt_Eclipse (Failed)
	 26 - vtkSlicerDoseVolumeHistogramModuleLogicTest_EclipseEnt_Eclipse_AutomaticOversampling (Failed)
	 27 - vtkSlicerDoseVolumeHistogramModuleLogicTest_DoseSurfaceHistogram_EclipseEnt_Base_Inside (Failed)
	 28 - vtkSlicerDoseVolumeHistogramModuleLogicTest_DoseSurfaceHistogram_EclipseEnt_Base_Outside (Failed)
	 29 - vtkSlicerDoseVolumeHistogramModuleLogicTest_DoseSurfaceHistogram_EclipseProstate_Base_Inside (Failed)
	 30 - vtkSlicerDoseVolumeHistogramModuleLogicTest_DoseSurfaceHistogram_EclipseProstate_Base_Outside (Failed)
	 47 - py_nomainwindow_PlmProtonDoseEngineTest (Failed)
	 54 - py_BatchStructureSetConversion (Failed)
	 62 - py_DrrImageComputationTest (Failed)
```

**Comment by lassoan** [comment]
Yes, let's switch switch to your fork then until a final solution is available out in the official Plastimatch repository. Thank you!

**Comment by lassoan** [comment]
I saw that you updated to use your fork, which looks good. Let me know if this is ready to be merged. Thanks!

**Comment by MichaelColonel** [comment]
I think it's ready.

Last tests:
```
76% tests passed, 17 tests failed out of 72

Label Time Summary:
plastimatch_slicer_drr                    =   0.20 sec*proc (1 test)
qSlicerBeamsModule                        =  25.09 sec*proc (3 tests)
qSlicerDicomRtImportExportModule          =  26.65 sec*proc (2 tests)
qSlicerDicomSroImportExportModule         =  13.24 sec*proc (2 tests)
qSlicerDoseAccumulationModule             =  14.27 sec*proc (2 tests)
qSlicerDoseComparisonModule               =  14.32 sec*proc (2 tests)
qSlicerDoseVolumeHistogramModule          =  13.60 sec*proc (2 tests)
qSlicerDosxyzNrc3dDoseFileReaderModule    =  12.07 sec*proc (2 tests)
qSlicerDrrImageComputationModule          =  19.53 sec*proc (3 tests)
qSlicerIsodoseModule                      =  16.53 sec*proc (2 tests)
qSlicerPinnacleDvfReaderModule            =  11.23 sec*proc (2 tests)
qSlicerPlanarImageModule                  =  10.90 sec*proc (2 tests)
qSlicerPlastimatchPyModule                =  12.90 sec*proc (2 tests)
qSlicerPlmProtonDoseEngineModule          =  19.40 sec*proc (2 tests)
qSlicerRoomsEyeViewModule                 =  20.64 sec*proc (3 tests)
qSlicerSegmentComparisonModule            =  14.33 sec*proc (2 tests)
qSlicerVffFileReaderModule                =  11.41 sec*proc (2 tests)

Total Test time (real) = 328.45 sec

The following tests FAILED:
	  1 - qSlicerBeamsModuleGenericTest (Failed)
	  2 - qSlicerBeamsModuleWidgetGenericTest (Failed)
	  4 - qSlicerIsodoseModuleGenericTest (Failed)
	  5 - qSlicerIsodoseModuleWidgetGenericTest (Failed)
	  6 - vtkSlicerIsodoseModuleLogicTest_EclipseProstate (Failed)
	 12 - py_DicomRtImportTest (Failed)
	 18 - vtkSlicerDoseVolumeHistogramModuleLogicTest_EclipseProstate_Base (Failed)
	 19 - vtkSlicerDoseVolumeHistogramModuleLogicTest_EclipseProstate_CERR (Failed)
	 20 - vtkSlicerDoseVolumeHistogramModuleLogicTest_EclipseEnt_CERR (Failed)
	 22 - vtkSlicerDoseVolumeHistogramModuleLogicTest_EclipseEnt_Eclipse (Failed)
	 26 - vtkSlicerDoseVolumeHistogramModuleLogicTest_EclipseEnt_Eclipse_AutomaticOversampling (Failed)
	 27 - vtkSlicerDoseVolumeHistogramModuleLogicTest_DoseSurfaceHistogram_EclipseEnt_Base_Inside (Failed)
	 28 - vtkSlicerDoseVolumeHistogramModuleLogicTest_DoseSurfaceHistogram_EclipseEnt_Base_Outside (Failed)
	 29 - vtkSlicerDoseVolumeHistogramModuleLogicTest_DoseSurfaceHistogram_EclipseProstate_Base_Inside (Failed)
	 30 - vtkSlicerDoseVolumeHistogramModuleLogicTest_DoseSurfaceHistogram_EclipseProstate_Base_Outside (Failed)
	 47 - py_nomainwindow_PlmProtonDoseEngineTest (Failed)
	 54 - py_BatchStructureSetConversion (Failed)
```

**Review by lassoan — APPROVED** [review]
Thank you, let's merge this to fix the build errors on linux and mac. We can revert to the official Plastimatch repository once its ITK compatibility issue is fixed.

**Pull request merged**
